### ISSUE TITLE
Scroll to bottom after refresh

### ISSUE THREAD

**Issue by 1RV34** [Waterflames/AutoRefresh#1]
I first just want to say, thanks for this simple but incredibly useful plugin. :)

I would like it if there would be an option to scroll to the bottom after the refresh too, this would be useful for log files that append to the end of the file.

**Comment by Waterflames** [comment]
Implemented in commit 2eec030 
Released in release 1.0.1

Get the latest version and select one the last three lines, AutoRefresh will then scroll to the bottom of the file after reload
