### ISSUE TITLE
Enable AutoRefresh not found in command pallete 

### ISSUE THREAD

**Issue by iulian0512** [Waterflames/AutoRefresh#10]

**Comment by Wouterdek** [comment]
What version of Sublime text are you using? What OS are you using? Did you install the plugin through the package control, or manually?

**Comment by iulian0512** [comment]
3.1.1 build 3176 , windows 10 x64 1803 instalation through package control

**Comment by Wouterdek** [comment]
I just tried installing the plugin on a fresh installation of Sublime text, same version and environment as you, and it seems to work fine. Are there any errors in the output in the console? Have you tried reinstalling the plugin/sublime?
