### ISSUE TITLE
How can I change default interval??

### ISSUE THREAD

**Issue by winternet-studio** [Waterflames/AutoRefresh#2]
How can I change the default interval? I find no package settings for this package in the menu Preferences > Package Settings!

**Comment by dullduck** [comment]
i have the same question,above.

**Comment by Waterflames** [comment]
Create a settings file called AutoRefresh.sublime-settings and set the setting auto_refresh_rate to how many seconds long you want the interval to be.

**Comment by dullduck** [comment]
THANKS.   but ,i find a strange problem.when i first modify a file on disk(opened by sublime text 3) use vi. sublime does not reload the file.only,when i open the file again with vi ,sublime reload the file.

**Comment by dullduck** [comment]
I update sublime to 'Bulid 3114'. The problem gone. Thank you!
