### ISSUE TITLE
Can't enable autorefresh

### ISSUE THREAD

**Issue by matthew-groth** [Waterflames/AutoRefresh#3]
I just installed this via Package Control, and I noticed it is still not refreshing. According to the readme I need to enable it via command, but I am having no luck getting that to work:

>>> Enable Autorefresh
  File "<string>", line 1
    Enable Autorefresh
                     ^
SyntaxError: unexpected EOF while parsing
>>> enable_auto_refresh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'enable_auto_refresh' is not defined

**Comment by Waterflames** [comment]
It seems to work fine for me on the latest version of Sublime Text 3.

Are you using Sublime Text 2 or 3?
What version are you using?
What OS are you using?
Did you simply install the plugin through the package manager or did you unpack the plugin?

**Comment by matthew-groth** [comment]
I am using Stable Channel build 3126 on Mac OSX 10.12.3.

I installed through Package Control. If I should test a manual install, how exactly would do that? I am new to Sublime Text.

**Comment by Waterflames** [comment]
It seems to work fine for me on Mac OSX aswell.
Try to install it manually:
1) Uninstall AutoRefresh using the package manager
2) Download https://github.com/Waterflames/AutoRefresh/archive/master.zip
3) Open your sublime packages folder (see http://stackoverflow.com/a/7866230)
4) Extract the zip you just downloaded to this folder
5) Restart sublime.

**Comment by matthew-groth** [comment]
Got it! Thanks for the help. Turns out I was mixing up the command palette and the console.
