### ISSUE TITLE
Autorefresh overwrites unsaved changes

### ISSUE THREAD

**Issue by matthew-groth** [Waterflames/AutoRefresh#6]
1. enable autorefresh on a file
2. edit file without saving

It is reverted back to the last save on refresh.

**Comment by Waterflames** [comment]
What behavior would you expect?

**Comment by matthew-groth** [comment]
Perhaps at every refresh cycle there could be an additional check to make sure there are no unsaved changes. I would expect the refresh to only occur when there are no unsaved changes.

I believe this is how Atom works.

**Comment by Waterflames** [comment]
Fixed in e51a46b
